"""GitHub PR creation scaffolding - dry-run and payload generation."""

from app.core.config import get_settings
from app.integrations.github.models import PRPayload
from app.schemas.remediation import RemediationRecommendation


def validate_github_config() -> tuple[bool, str]:
    """Validate GitHub config from env. Returns (valid, message)."""
    settings = get_settings()
    if not settings.github_token:
        return False, "GITHUB_TOKEN not set"
    if not settings.github_owner:
        return False, "GITHUB_OWNER not set"
    if not settings.github_repo:
        return False, "GITHUB_REPO not set"
    return True, "OK"


def prepare_pr_payload(
    recommendations: list[RemediationRecommendation],
    manifest_path: str = "requirements.txt",
    dry_run: bool = True,
) -> PRPayload:
    """
    Generate PR payload for remediation branch.
    Does not push or create PR; returns what would be created.
    """
    settings = get_settings()
    if dry_run or settings.github_dry_run:
        pass  # No side effects

    branch_name = "security/remediation-deps"
    if recommendations:
        pkgs = "-".join(r.package for r in recommendations[:3])
        if len(recommendations) > 3:
            pkgs += f"-and-{len(recommendations) - 3}-more"
        branch_name = f"security/remediation-{pkgs}"[:80]

    pr_title = "chore(security): remediate vulnerable dependencies"
    pr_body = "## Remediation Summary\n\n"
    pr_body += "This PR updates vulnerable dependencies based on scan results.\n\n"
    pr_body += "### Recommendations\n\n"
    for r in recommendations:
        pr_body += f"- **{r.package}**: {r.current_version} → {r.recommended_version}"
        if r.manual_review_required:
            pr_body += " ⚠️ **Manual review required**"
        pr_body += "\n"
        pr_body += f"  - Vulns: {', '.join(r.vulnerability_ids)}\n"
        pr_body += f"  - Rationale: {r.rationale}\n\n"

    pr_body += "---\n*Generated by TaskForge Security. Review before merging.*\n"

    commit_message = "chore(security): remediate vulnerable dependencies\n\n"
    for r in recommendations:
        commit_message += f"- {r.package}: {r.current_version} -> {r.recommended_version}\n"

    # Build file changes (simplified: would need to read actual manifest and apply updates)
    file_changes: list[dict[str, str]] = []
    for r in recommendations:
        if r.recommended_version != r.current_version:
            # Placeholder: actual impl would read file, apply change
            file_changes.append(
                {
                    "path": manifest_path,
                    "content": f"# {r.package} would be updated to {r.recommended_version}",
                }
            )

    return PRPayload(
        branch_name=branch_name,
        pr_title=pr_title,
        pr_body=pr_body,
        commit_message=commit_message,
        file_changes=file_changes,
    )
